apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-sleep-cm
  namespace: default
data:
  SLEEP_INTERVAL: "120"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-second-cm
  namespace: default
data:
  SLEEP_INTERVAL_TWO: "20"
