apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-ns-quota
  namespace: default
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 8Gi
    requests.cpu: "2"
    requests.memory: 5Gi
    pods: "10"