apiVersion: v1
kind: Secret
metadata:
  name: myapp-restart-secret
  namespace: default
type: Opaque
data:
  RESTART_COUNT: "dHdvCg=="

---
apiVersion: v1
kind: Secret
metadata:
  name: myapp-second-secret
  namespace: default
type: Opaque
data:
  RESTART_COUNT: "dHdvCg=="