#the "my-service-account" in the "my-namespace" namespace is granted cluster-level permissions to interact with nodes in the cluster.

#ClusterRole named "node-manager" that grants "get" and "update" permissions for nodes across all namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-manager
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "update"]

---
#ClusterRoleBinding named "node-manager-binding" to associate the ClusterRole with a ServiceAccount named "my-service-account" in the "my-namespace" namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-manager-binding
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: my-namespace
roleRef:
  kind: ClusterRole
  name: node-manager
  apiGroup: rbac.authorization.k8s.io
