#With this configuration, user "alice" has permission to retrieve and list Pods within the "my-namespace" namespace but cannot 
#perform other actions or access resources in other namespaces.

#A Role named "pod-reader" is defined in the "my-namespace" namespace, granting permissions to "get" and "list" Pods.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-namespace
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
  resourceNmes: ["silver-pod", "blue-pod"]

  ---
#A RoleBinding named "read-pods-binding" associates the "pod-reader" Role with the user "alice" within the "my-namespace" namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: my-namespace
subjects:
- kind: User
  name: alice
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io